[tool.poetry]
name = "har2tree"
version = "1.0"
description = "HTTP Archive (HAR) to ETE Toolkit generator"
authors = ["Raphaël Vinot <raphael.vinot@circl.lu>"]
license = "BSD-3-Clause"
repository = "https://github.com/viper-framework/har2tree"

readme = "README.md"

classifiers = [
    'License :: OSI Approved :: BSD License',
	'Operating System :: POSIX :: Linux',
	'Intended Audience :: Science/Research',
	'Intended Audience :: Telecommunications Industry',
	'Intended Audience :: Information Technology',
	'Programming Language :: Python :: 3',
	'Topic :: Security',
	'Topic :: Internet'
]

include = ["har2tree/data/img/*.png"]

[tool.poetry.scripts]
har2tree = 'bin/har2tree'

[tool.poetry.dependencies]
python = "^3.6"
ete3 = "^3.1.1"
beautifulsoup4 = "^4.8.2"
lxml = "^4.4.2"
six = "^1.14.0"
publicsuffix2 = "^2.20191221"

[tool.poetry.dev-dependencies]
coverage = "^5.0.3"
coveralls = "^1.10.0"
codecov = "^2.0.15"
mypy = "^0.761"
nose = "^1.3.7"
ipython = "^7.12.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
